#!/usr/bin/env python3
"""Regenerate the Media section's video cards from the YouTube playlist.

YouTube's RSS feed sends no CORS headers, so the page cannot fetch it in the
browser. Instead this runs in CI: it pulls the playlist, self-hosts each
thumbnail as a WebP, and rewrites the block between the YT:CARDS markers in
index.html. The published page stays static — no runtime request to YouTube.

Thumbnails are named by video id, so a re-upload (new id) is picked up as a
new file and the stale one is pruned.

Usage: python3 scripts/sync_youtube.py [--check]
       --check exits 1 if index.html would change, without writing.
"""

import html
import io
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

from PIL import Image

PLAYLIST_ID = "PLFe15SxHKlqw"
FEED = f"https://www.youtube.com/feeds/videos.xml?playlist_id={PLAYLIST_ID}"
ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
START = "<!-- YT:CARDS:START — generated by scripts/sync_youtube.py; do not edit by hand -->"
END = "<!-- YT:CARDS:END -->"

# Thumbnails are displayed ~275 CSS px wide; 960 covers 2x displays with room
# to spare and keeps each file well under 100 KB.
THUMB_W, THUMB_H, THUMB_Q = 960, 540, 68
NS = {"a": "http://www.w3.org/2005/Atom", "yt": "http://www.youtube.com/xml/schemas/2015"}
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def get(url: str, timeout: int = 30) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "pmuguda-portfolio-sync/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def clean_title(raw: str) -> str:
    """Drop the channel suffix and curl straight quotes for typographic parity."""
    title = re.sub(r"\s*\|\s*Range\s*&\s*Azimuth\s*$", "", raw).strip()
    return re.sub(r'"([^"]*)"', "“\\1”", title)


def fetch_playlist() -> list[dict]:
    root = ET.fromstring(get(FEED))
    videos = []
    for entry in root.findall("a:entry", NS):
        published = entry.find("a:published", NS).text
        videos.append({
            "id": entry.find("yt:videoId", NS).text,
            "title": clean_title(entry.find("a:title", NS).text),
            "date": f"{MONTHS[int(published[5:7]) - 1]} {published[:4]}",
        })
    if not videos:
        raise SystemExit("playlist returned no videos — refusing to blank the section")
    return videos


def ensure_thumb(video_id: str) -> str:
    """Download and convert the thumbnail if it isn't already on disk."""
    name = f"yt-{video_id}.webp"
    if (ROOT / name).exists():
        return name
    for quality in ("maxresdefault", "hqdefault"):
        try:
            data = get(f"https://i.ytimg.com/vi/{video_id}/{quality}.jpg")
        except Exception:
            continue
        img = Image.open(io.BytesIO(data)).convert("RGB")
        # hqdefault is 4:3 with letterbox bars; crop back to the 16:9 frame.
        if abs(img.width / img.height - 16 / 9) > 0.05:
            bar = round((img.height - img.width * 9 / 16) / 2)
            img = img.crop((0, bar, img.width, img.height - bar))
        img.resize((THUMB_W, THUMB_H), Image.LANCZOS).save(
            ROOT / name, "WEBP", quality=THUMB_Q, method=6)
        print(f"  + thumbnail {name}")
        return name
    raise SystemExit(f"no thumbnail available for {video_id}")


def render(videos: list[dict]) -> str:
    cards = []
    for i, v in enumerate(videos, 1):
        title = html.escape(v["title"])
        cards.append(f"""                <a class="yt-card" href="https://www.youtube.com/watch?v={v['id']}&list={PLAYLIST_ID}" target="_blank" rel="noopener noreferrer">
                    <div class="yt-thumb">
                        <img src="{v['thumb']}" width="{THUMB_W}" height="{THUMB_H}" loading="lazy" decoding="async"
                             alt="Video thumbnail: {title}">
                        <span class="yt-play" aria-hidden="true"></span>
                    </div>
                    <div class="yt-body">
                        <div class="yt-ep">EP {i:02d} &nbsp;·&nbsp; {v['date']}</div>
                        <div class="yt-title">{title}</div>
                        <span class="yt-watch">Watch on YouTube &nbsp;→</span>
                    </div>
                </a>""")
    return f'{START}\n            <div class="yt-grid">\n' + "\n".join(cards) + f"\n            </div>\n            {END}"


def prune(keep: set[str]) -> None:
    for f in ROOT.glob("yt-*.webp"):
        if f.name not in keep:
            f.unlink()
            print(f"  - pruned {f.name}")


def main() -> int:
    check = "--check" in sys.argv
    videos = fetch_playlist()
    print(f"playlist: {len(videos)} video(s)")
    for v in videos:
        print(f"  {v['id']}  {v['date']}  {v['title']}")

    source = INDEX.read_text(encoding="utf-8")
    if START not in source or END not in source:
        raise SystemExit("marker comments missing from index.html")

    if not check:
        for v in videos:
            v["thumb"] = ensure_thumb(v["id"])
    else:
        for v in videos:
            v["thumb"] = f"yt-{v['id']}.webp"

    updated = re.sub(re.escape(START) + r".*?" + re.escape(END),
                     lambda _: render(videos), source, flags=re.S)

    if updated == source:
        print("index.html already up to date")
        return 0
    if check:
        print("index.html is OUT OF DATE")
        return 1

    INDEX.write_text(updated, encoding="utf-8")
    prune({v["thumb"] for v in videos})
    print("index.html updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
